### ISSUE TITLE
Issue with MOT17 

### ISSUE THREAD

**Issue by HemangParmar17** [ocetintas/MPNTrackSeg#3]
Hi, Thank you for the code.
I have a question about running MOT17.
We ran the old code of mot_neural_solver (https://github.com/dvl-tum/mot_neural_solver) for MOT17, Where the accuracy of MOT17 was low. So we tried this code as you have used edge classification + mask prediction to improve the accuracy.
But unfortunately, we are facing issues with the MOT17 train as it gives an error AttributeError: 'NoneType' object has no attribute ‘to. pickle’.

Can we run MOT17 with the same code as MOTS20? 

Kindly let us know how to proceed further.

Thank you.

**Comment by ocetintas** [comment]
Hi,
Unfortunately, this code base is not directly compatible with MOT17 training or evaluation so you might need to fix some bugs if you want to apply it for MOT. 

I'd suggest you use the original mot_neural_solver repo for MOT because the MOTS20 dataset doesn't contain all MOT17 sequences; therefore, you won't be able to train your model on the full MOT17 dataset with this code base. In addition, MPNTrack has some implementation details that give you a boost for MOT such as frame sampling which is not used here for MOTS. I am not sure why you got a lower accuracy for MOT17 with mot_neural_solver repo but tracking scores (MOTA, IDF1) should be similar to the ones reported in the CVPR paper.

**Comment by HemangParmar17** [comment]
Thank you for the response.
As you explained, MPNTrackSeg is not compatible with MOT17. Can you please explain frame sampling or how to implement it in the mot-neural-solver? if you can give us some hints or ideas about the code it would be a great help.
